"""
planner_service.py

The Planner Agent -- Part 1 of the Study-Material-to-Video pipeline. Takes
a topic, produces a coherent shot-by-shot teaching sequence. Everything
downstream (Visual Agent, Narration Agent, Assembler) depends on this
output's shape being right.
"""

import os
from groq import Groq
from dotenv import load_dotenv

from schemas import ShotList

load_dotenv()
client = Groq(api_key=os.environ.get("GROQ_API_KEY"))
MODEL = "openai/gpt-oss-120b"

WORDS_PER_MINUTE = 150  # average narration speaking rate (Q4)


def _estimate_duration_seconds(narration: str) -> float:
    """
    Q4, in code: word count / speaking rate * 60. Deliberately NOT asking
    the LLM to do this math -- computed here in plain Python, which is
    reliable, instead of trusting the LLM's arithmetic (same reasoning as
    why Study Companion validated option counts in code, not just via
    the schema).
    """
    word_count = len(narration.split())
    return round((word_count / WORDS_PER_MINUTE) * 60, 1)


def generate_shot_list(
    topic: str, min_shots: int = 3, max_shots: int = 6, instructions: str = ""
) -> dict:
    """
    Returns a dict shaped like ShotList, with each shot's
    estimated_duration_seconds computed by OUR code after the LLM call,
    not generated by the LLM itself.

    instructions: OPTIONAL free-text constraints from the user (e.g.
    "keep it beginner-friendly", "focus more on time complexity"). Empty
    string (the default) means no extra constraints -- the Planner uses
    its own judgment exactly as before this parameter existed.
    """
    system_prompt = (
        "You are an instructional designer planning a short educational "
        "explainer video. Break the given topic into a coherent teaching "
        "sequence, not a random list of facts. Each shot must have a "
        "clear PURPOSE that fits into a natural learning flow -- for "
        "example: a 'hook' shot that motivates why the topic matters, a "
        "'definition' shot explaining the core concept clearly, one or "
        "more 'example' shots walking through a concrete case step by "
        "step, and a 'recap' shot summarizing the key takeaway. Shots "
        "must build on each other in order -- do not repeat the same "
        "idea across shots, and do not jump to advanced details before "
        "the basics are established.\n\n"
        "CRITICAL: every single shot -- including the recap -- must be "
        "strictly about the ONE topic given to you, and nothing else. "
        "Do NOT introduce terminology, steps, or concepts from a "
        "DIFFERENT algorithm or topic, even if it seems like a natural "
        "comparison. For example, if the topic is bubble sort, never "
        "mention dividing the array, discarding halves, or comparing "
        "middle elements -- those belong to binary search, a different "
        "algorithm, and do not belong anywhere in this video."
    )

    user_prompt = (
        f"Topic: {topic}\n\n"
        f"First, invent ONE concrete, specific example you will use for "
        f"the ENTIRE video -- e.g. if this is a sorting or searching "
        f"algorithm, pick one specific array of 6-8 numbers. Put this in "
        f"'example_data' as a short string (e.g. '[8, 3, 1, 7, 2, 5, 6, "
        f"4]'). Every shot's narration AND visual_description must reuse "
        f"THIS SAME example -- do not invent a different array or a new "
        f"example partway through. Consistency across shots matters more "
        f"than variety.\n\n"
        f"Produce between {min_shots} and {max_shots} shots total (Q3's "
        f"scope control) -- enough to actually teach the topic clearly, "
        f"but not so many that the video becomes bloated. Each shot needs: "
        f"a 'purpose', 'narration' (the spoken text for that shot, "
        f"conversational and clear, roughly 20-50 words), and a "
        f"'visual_description' (plain English -- describe WHAT should be "
        f"shown on screen using the SAME example_data above, not how to "
        f"code it). Prefer showing the actual numbers/elements from "
        f"example_data over abstract icons, generic diagrams, or "
        f"metaphors (e.g. for a 'best case' or complexity shot, show the "
        f"same array already in its best-case state with a label, rather "
        f"than an abstract timer or loop icon)."
    )

    if instructions:
        # User-provided, OPTIONAL. Appended last so it reads as an
        # additional constraint on top of everything above, not a
        # replacement for the core structural requirements (shot count,
        # example_data consistency, topic-only content).
        user_prompt += (
            f"\n\nThe user also gave these specific instructions for this "
            f"video -- follow them as closely as possible without "
            f"breaking the requirements above: {instructions}"
        )

    response = client.chat.completions.create(
        model=MODEL,
        messages=[
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_prompt},
        ],
        temperature=0.4,
        max_tokens=3500,
        response_format={
            "type": "json_schema",
            "json_schema": {
                "name": "shot_list",
                "strict": True,  # learned this the hard way last project
                "schema": ShotList.model_json_schema(),
            },
        },
    )

    import json
    shot_list = json.loads(response.choices[0].message.content)

    # Manual validation the schema can't fully guarantee (same lesson as
    # Study Companion's options-length bug) -- check shot COUNT is
    # actually within range, not just that each shot has the right fields.
    num_shots = len(shot_list["shots"])
    if not (min_shots <= num_shots <= max_shots):
        raise ValueError(
            f"Expected {min_shots}-{max_shots} shots, got {num_shots}"
        )

    # Compute duration for each shot HERE, in code -- not trusting the LLM.
    total_duration = 0.0
    for shot in shot_list["shots"]:
        duration = _estimate_duration_seconds(shot["narration"])
        shot["estimated_duration_seconds"] = duration
        total_duration += duration

    shot_list["total_estimated_duration_seconds"] = round(total_duration, 1)

    return shot_list